# Generated by Django 4.2.2 on 2023-06-14 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('key_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'verbose_name': 'Aluguel', 'verbose_name_plural': 'Alugueis'},
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='chave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alugueis', to='key_master.chave'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
