# Generated by Django 4.2.2 on 2023-06-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_master', '0002_alter_aluguel_options_alter_aluguel_chave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
