# Generated by Django 4.2.2 on 2023-06-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_master', '0005_alter_chave_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
