# Generated by Django 4.2.1 on 2023-05-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('key_aplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='identificador',
        ),
        migrations.AlterField(
            model_name='chave',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_aplication.sala'),
        ),
    ]
