# Generated by Django 4.2.1 on 2023-05-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_aplication', '0002_remove_chave_identificador_alter_chave_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='disponibilidade',
            field=models.BooleanField(default=True, verbose_name='Disponibilidade:'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_retirada',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
