# Generated by Django 4.2.1 on 2023-05-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_aplication', '0003_alter_chave_disponibilidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='user',
            new_name='usuario',
        ),
    ]
