# Generated by Django 4.2.1 on 2023-05-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_aplication', '0005_remove_funcionario_funcao_remove_funcionario_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='identificador',
        ),
    ]
