# Generated by Django 4.2.1 on 2023-05-29 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('key_aplication', '0006_remove_chave_identificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluguelChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='chave',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='chave',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='funcionario',
        ),
        migrations.RenameField(
            model_name='chave',
            old_name='disponibilidade',
            new_name='disponivel',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='identificador',
        ),
        migrations.AddField(
            model_name='chave',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chave',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='key_aplication.sala'),
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
        migrations.AddField(
            model_name='aluguelchave',
            name='chave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_aplication.chave'),
        ),
        migrations.AddField(
            model_name='aluguelchave',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_aplication.funcionario'),
        ),
    ]
