# Generated by Django 4.2.1 on 2023-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_aplication', '0007_aluguelchave_remove_reserva_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='descricao',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
