# Generated by Django 4.2.1 on 2023-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_aplication', '0015_remove_funcionario_user_funcionario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='usuario',
            new_name='user',
        ),
    ]
